# -*- coding: utf-8 -*-
"""Hebbs_Net_AND.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16KlofdL_pfzlZgRczIeEHtawCSmrmkHu
"""

# ============================================================
# HEBBIAN NETWORK - AND GATE (SIMPLE)
# Program by: Samip Khadka
# Roll No: 36
# ============================================================

print("="*50)
print("  HEBBIAN NETWORK: AND GATE")
print("  Program by: Samip Khadka")
print("  Roll No: 36")
print("="*50)

# ============================================================
# DATA: AND Gate (Bipolar: 1 = True, -1 = False)
# ============================================================

data = [
    ([1, 1], 1),
    ([1, -1], -1),
    ([-1, 1], -1),
    ([-1, -1], -1)
]

print("\nAND Gate Truth Table:")
print("  x1  x2  |  Target")
print("  ---------------")
for x, t in data:
    print(f"  {x[0]:2}  {x[1]:2}  |    {t:2}")

# ============================================================
# HEBBIAN NEURON
# ============================================================

w1 = 0.0
w2 = 0.0
bias = 0.0
eta = 1.0

print("\n" + "="*50)
print("  TRAINING")
print("="*50)
print(f"Initial: w1={w1}, w2={w2}, bias={bias}, η={eta}\n")

# ============================================================
# TRAIN FOR 5 EPOCHS
# ============================================================

for epoch in range(1):
    print(f"Epoch {epoch+1}")
    print("-" * 30)

    for x, target in data:
        x1, x2 = x
        y = target  # Use target as output for Hebbian learning

        # Hebbian Rule: Δw = η × x × y
        dw1 = eta * x1 * y
        dw2 = eta * x2 * y
        db = eta * y

        # Update
        w1 += dw1
        w2 += dw2
        bias += db

        print(f"  ({x1:2}, {x2:2}) → y={y:2} | Δw=({dw1:3.0f}, {dw2:3.0f}) | w=({w1:3.0f}, {w2:3.0f}) bias={bias:3.0f}")

# ============================================================
# RESULT
# ============================================================

print("\n" + "="*50)
print("  FINAL WEIGHTS")
print("="*50)
print(f"  w1 = {w1:.0f}, w2 = {w2:.0f}, bias = {bias:.0f}")

print("\n" + "="*50)
print("  TESTING")
print("="*50)

print("\n  x1  x2  |  yin  |  y  |  Expected")
print("  " + "-"*30)

for x, target in data:
    x1, x2 = x
    yin = x1*w1 + x2*w2 + bias
    y = 1 if yin >= 0 else -1
    status = "✅" if y == target else "❌"
    print(f"  {x1:2}  {x2:2}  |  {yin:4.0f}  |  {y:2}  |    {target:2}     {status}")

print("\n" + "="*50)
if y == target:
    print(" AND Gate Learned Successfully!")
else:
    print(" AND Gate NOT Learned!")
print("="*50)