# -*- coding: utf-8 -*-
"""Perceptron_AND.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g-HwOC5ngwLvbOnHyruJtF_zCZ9N_d5b
"""

print("="*50)
print("  PERCEPTRON LEARNING: AND GATE")
print("  Program by: Samip Khadka")
print("  Roll No: 36")
print("="*50)

# ============================================================
# DATA: AND Gate (Bipolar: 1 = True, -1 = False)
# ============================================================

data = [
    ([1, 1], 1),
    ([1, -1], -1),
    ([-1, 1], -1),
    ([-1, -1], -1)
]

print("\nAND Gate Truth Table:")
print("  x1  x2  |  Target")
print("  ---------------")
for x, t in data:
    print(f"  {x[0]:2}  {x[1]:2}  |    {t:2}")

# ============================================================
# PERCEPTRON NEURON
# ============================================================

w1 = 0.0
w2 = 0.0
bias = 0.0
eta = 1

print("\n" + "="*50)
print("  TRAINING")
print("="*50)
print(f"Initial: w1={w1}, w2={w2}, bias={bias}, η={eta}\n")

# ============================================================
# ACTIVATION FUNCTION
# ============================================================

def activation(x):
    if x >= 0:
        return 1
    elif x == 0:
        return 0
    else:
        return -1
    # return 1 if x >= 0 else -1

def predict(x1, x2):
    yin = x1*w1 + x2*w2 + bias
    return activation(yin)

# ============================================================
# TRAINING WITH EARLY STOPPING
# ============================================================

for epoch in range(10):
    print(f"Epoch {epoch+1}")
    print("-" * 30)

    correct = 0

    for x, target in data:
        x1, x2 = x
        y = predict(x1, x2)

        # Simplified Perceptron Rule: Update only when wrong
        if y != target:
            dw1 = eta * x1 * target
            dw2 = eta * x2 * target
            db = eta * target
            w1 = w1 + dw1
            w2 = w2 + dw2
            bias = bias + db

        else:
            dw1 = 0
            dw2 = 0
            db = 0

        if y == target:
            correct += 1

        status = "✅" if y == target else "❌"
        print(f"  ({x1:2}, {x2:2}) → y={y:2}, t={target:2} {status} | Δw=({dw1:4.1f}, {dw2:4.1f}) | w=({w1:4.1f}, {w2:4.1f}) bias={bias:4.1f}")

    print(f"  Accuracy: {correct}/4")

    if correct == 4:
        print(f"\n✅ ALL PATTERNS CORRECT! Stopping at Epoch {epoch+1}")
        break

# ============================================================
# RESULT
# ============================================================

print("\n" + "="*50)
print("  FINAL WEIGHTS")
print("="*50)
print(f"  w1 = {w1:.1f}, w2 = {w2:.1f}, bias = {bias:.1f}")

print("\n" + "="*50)
print("  TESTING")
print("="*50)

print("\n  x1  x2  |  yin  |  y  |  Expected")
print("  " + "-"*30)

for x, target in data:
    x1, x2 = x
    yin = x1*w1 + x2*w2 + bias
    y = activation(yin)
    status = "✅" if y == target else "❌"
    print(f"  {x1:2}  {x2:2}  |  {yin:4.1f}  |  {y:2}  |    {target:2}     {status}")

print("\n" + "="*50)
print("✅ AND Gate Learned Successfully!")
print("   Perceptron Rule: Update only when wrong")
print("   Simplified: w = w + η × x × target")
print("="*50)